---
title: "QA Stat. profiles Unsat Zone"
author: "G.Bier"
date: "March, 25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Research Question Stat. Profils

Select one of the soils in de "soil type" box of the **stat_profiles_play.R** script. Set the groundwater table to -250 cm and change the flux rate such that the "red" lines matches the blue dashed lines in both panels.

1.  What flux rate is set for this?
    1.  *This will be at q=0.0 cm/d*
2.  What plot is shown in the left and the right panel?
    1.  *left pressure head profile and right moisture content profile*
3.  Compare the pressure head $\psi$ with the elevation $z$ (directed positive upward)
    1.  *They are equal with different signs*
4.  What can you say about the pressure gradient in this situation?
    1.  $\frac{\partial \psi}{\partial z}= -1$
5.  So can you now argue that indeed the $q=0.0$ in this case inspecting the Darcy-Buckingham equation
    1.  $q=-K(\psi)\left( \frac{ \partial \psi}{\partial z} + 1 \right)=K(\psi)(-1+1)=0$
6.  Why is the moisture profile not linear?
    1.  *The soils capacity to "suck" water up and to retain the water in the pores (small films of water around the granulates) is not linear but strongly non linear. Or approach it in another way the pressure gradient, as within the saturated zone' determines flow.*
7.  Set the water table to 100 cm below surface. Select B5 Coarse sand. How much capillary rise can you generate with this soil type without getting invalid profiles (extreme high negative pressures (\< 16000 cm) moisture profile constant at the top)
    1.  *about -0.1 cm/d so about 1 mm/d still*
8.  Repeat this for a Loam (B13) and non-Loamy sand (B1). And what pressures (suction) are required at the surface to generate this cap. rise?
    1.  *B1 about 0.28 cm/d and psi -2700*
    2.  *B5 about 0.1 cm/d and psi 1150*
    3.  *B13 max. 1 cm/d ans psi 200*
9.  Set the depth 1500 cm. Why is the pressure profile very close to vertical? In other words, the pressure of the upper part is constant.
    1.  *The water table has no effect on the pressure since it's too deep/far away. Now flow is only generated by the gravity pull. In formula:* $q=-K(\psi)\left( \frac{ \partial \psi}{\partial z} + 1 \right)$ *since* $\psi$ *is constant in the upper part the pressure gradient becomes 0.0 :* $\frac {\partial \psi}{\partial z} = 0$. *This results in a flux rate equal to the hydraulic conductivity at this pressure (or moisture content)*
10. Set the soil to B10 Light Clay and set the recharge to 1 cm/d. Can you explain both graphs?
    1.  The soil is fully saturated now, this is illustrated in the moisture content profile. the whole profile has $\theta_{sat}$ The pressure profile shows positive pressure
